import { useState } from 'react'
import { Link } from 'react-router-dom'
import { projects, experiences, projectGroups } from './data/portfolioData'

export function Navigation() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><Link className="wordmark" to="/" aria-label="Ajay Suthaharan home">ajay<span>.</span></Link><button className="menu-toggle" aria-expanded={open} aria-controls="navigation" onClick={() => setOpen(!open)}>{open ? 'Close' : 'Menu'}</button><nav id="navigation" className={open ? 'navigation is-open' : 'navigation'} aria-label="Main navigation"><a href="/#experience" onClick={() => setOpen(false)}>Experience</a><a href="/#projects" onClick={() => setOpen(false)}>Projects</a><a href="/#contact" onClick={() => setOpen(false)}>Contact</a><a className="nav-resume" href="/resume.pdf" target="_blank" rel="noreferrer">Resume ↗</a></nav></header>
}
export function Footer() {
  return <footer id="contact" className="contact"><div><p className="eyebrow">GET IN TOUCH</p><h2>Let’s talk.</h2><a className="email-link" href="mailto:asuth075@uottawa.ca">asuth075@uottawa.ca ↗</a></div><div className="contact-links"><a href="https://github.com/Ajay757" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://linkedin.com/in/ajaysuthaharan/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="/resume.pdf" target="_blank" rel="noreferrer">Resume ↗</a></div><p className="footer-note">Ajay Suthaharan <span>Ottawa / Toronto, Canada</span></p></footer>
}
export default function App() {
  return <div className="site-shell"><a className="skip-link" href="#main">Skip to content</a><Navigation /><main id="main">
    <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">AJAY SUTHARAHAN · COMPUTER SCIENCE @ UOTTAWA</p><h1 id="hero-title">Building AI.<br /><span>Engineering what’s next.</span></h1><p className="hero-description">I build AI systems and backend applications, with experience in foundation-model research, statistical programming, and full-stack development.</p><div className="hero-actions"><a className="button primary" href="#projects">Explore my work ↓</a><a className="button secondary" href="/resume.pdf" target="_blank" rel="noreferrer">View resume ↗</a></div><p className="location"><span className="status-dot" />Based in Ottawa · Open to Ottawa & Toronto opportunities</p></div>
    <Link className="hero-feature" to="/projects/hiprex" aria-label="Explore HiPREX, my featured AI-agent project"><div className="feature-top"><span className="mini-icon">H</span><span>PROJECT SPOTLIGHT</span><span aria-hidden="true">↗</span></div><div className="memory-visual" aria-hidden="true"><div className="message-bubble">Remember my favorite color is blue.</div><div className="route-line"><span>PLAN</span><i /><span>UPDATE</span><i /><span>STORE</span></div><div className="state-block"><span>persistent state</span><code>favorite_color: <b>"blue"</b></code></div></div><div className="feature-bottom"><h2>HiPREX</h2><p>AI agents with memory.<br />Built around deterministic execution.</p><span className="text-link">Explore project ↗</span></div></Link></section>
    <section id="experience" className="section" aria-labelledby="experience-title"><div className="section-heading"><div><p className="eyebrow">01 / EXPERIENCE</p><h2 id="experience-title">Where I’ve contributed.</h2></div><span className="section-aside">Research. Data. Software.</span></div><p className="experience-intro">I’m a Computer Science co-op student at uOttawa, working across applied AI, statistical programming, and full-stack software. Here’s a closer look at my experience.</p><div className="experience-list">{experiences.map(exp => <article className="experience-row" key={exp.company}><div className={'company-mark '+exp.style} aria-hidden="true">{exp.mark}</div><div className="experience-body"><div className="experience-title"><h3>{exp.company}</h3>{exp.current && <span className="current-badge">Current</span>}</div><p className="role">{exp.role}</p><p className="experience-description">{exp.description}</p><details className="experience-details"><summary>More about my work <span aria-hidden="true">+</span></summary><div>{exp.details.map(([title,body])=><section key={title}><h4>{title}</h4><p>{body}</p></section>)}<ul className="tags">{exp.skills.map(skill=><li key={skill}>{skill}</li>)}</ul></div></details></div><p className="experience-date">{exp.period}</p></article>)}</div></section>
    <div id="projects" className="project-collection"><nav className="project-jump-links" aria-label="Project categories">{projectGroups.map(group=><a key={group.id} href={'#'+group.id}>{group.title}</a>)}</nav>{projectGroups.map(group=><section key={group.id} id={group.id} className="section project-group" aria-labelledby={group.id+'-title'}><div className="section-heading"><div><p className="eyebrow">{group.number} / SELECTED WORK</p><h2 id={group.id+'-title'}>{group.title}</h2></div><span className="section-aside">03 projects</span></div><div className="project-grid">{group.slugs.map(slug=>{const project=projects.find(p=>p.slug===slug);return <article className="project-card" key={project.slug}><Link to={'/projects/'+project.slug} className={'project-image '+project.slug} tabIndex={-1} aria-hidden="true">{project.image?<img src={project.image} alt="" loading="lazy" />:<div className="project-monogram"><span>Icarus</span><small>Personal AI assistant</small></div>}<span className="image-label">{project.status}</span></Link><div className="project-content"><p className="eyebrow">{project.category}</p><h3><Link to={'/projects/'+project.slug}>{project.title}</Link></h3><p>{project.description}</p>{project.tech.length>0&&<ul className="tags" aria-label="Technologies">{project.tech.map(tech=><li key={tech}>{tech}</li>)}</ul>}<div className="project-actions"><Link className="project-link" to={'/projects/'+project.slug}>About project ↗</Link>{project.links?.map(link=><a className="project-link live-link" key={link.url} href={link.url} target="_blank" rel="noreferrer">{link.label} ↗</a>)}</div></div></article>})}</div></section>)}</div>
  </main><Footer /></div>
}
